# Generated by Django 4.1.6 on 2023-07-20 19:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightnumber', models.CharField(default='AA 201', max_length=10, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(default='', max_length=50)),
                ('arrival_airport', models.CharField(default='', max_length=50)),
                ('departure_date', models.DateField(default='2022-01-01')),
                ('departure_time', models.TimeField(default='00:00')),
                ('available_seats', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60)])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=50)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('num_passengers', models.PositiveIntegerField(default=0)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flight_bookings_app.flight')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airports', to='flight_bookings_app.flight')),
                ('departure_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flight_bookings_app.flight')),
                ('departure_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_times', to='flight_bookings_app.flight')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_bookings_app.flight')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
