# Generated by Django 4.1.6 on 2023-07-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_bookings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='price',
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(default='2023-07-07'),
        ),
    ]
